static_routes:
- vrf: MGMT
  destination_address_prefix: 0.0.0.0/0
  gateway: 172.100.100.1
service_routing_protocols_model: multi-agent
ip_routing: true
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
name_server:
  source:
    vrf: MGMT
  nodes:
  - 1.1.1.1
  - 8.8.8.8
spanning_tree:
  mode: mstp
  mst_instances:
    '0':
      priority: 16384
  no_spanning_tree_vlan: 4094
local_users:
  test_admin:
    privilege: 15
    role: network-admin
    sha512_password: $6$7GTxsrRjnwheeKfR$zhJ8qycVjAJz41rf5JRSfWIzp93IL5WL7sMS/Taz1yfShz.MAnoajCf7R2n1/EZW7PN5QA3Huayl0lVQesBYN1
vrfs:
  MGMT:
    ip_routing: false
management_interfaces:
  Management1:
    description: oob_management
    shutdown: false
    vrf: MGMT
    ip_address: 172.100.100.8/24
    gateway: 172.100.100.1
    type: oob
management_api_http:
  enable_vrfs:
    MGMT: {}
  enable_https: true
vlans:
  4094:
    tenant: system
    name: MLAG_PEER
    trunk_groups:
    - MLAG
  112:
    tenant: Tenant_A
    name: Tenant_A_OP_Zone_3
  113:
    tenant: Tenant_A
    name: Tenant_A_OP_Zone_4
vlan_interfaces:
  Vlan4094:
    description: MLAG_PEER
    shutdown: false
    ip_address: 10.255.252.8/31
    no_autostate: true
    mtu: 9000
port_channel_interfaces:
  Port-Channel3:
    description: MLAG_PEER_leaf06-dc1_Po3
    type: switched
    shutdown: false
    vlans: 2-4094
    mode: trunk
    trunk_groups:
    - MLAG
  Port-Channel1:
    description: DC1_SVC01_Po5
    type: switched
    shutdown: false
    vlans: 112-113
    mode: trunk
    mlag: 1
ethernet_interfaces:
  Ethernet3:
    peer: leaf06-dc1
    peer_interface: Ethernet3
    peer_type: mlag_peer
    description: MLAG_PEER_leaf06-dc1_Ethernet3
    type: switched
    shutdown: false
    channel_group:
      id: 3
      mode: active
  Ethernet4:
    peer: leaf06-dc1
    peer_interface: Ethernet4
    peer_type: mlag_peer
    description: MLAG_PEER_leaf06-dc1_Ethernet4
    type: switched
    shutdown: false
    channel_group:
      id: 3
      mode: active
  Ethernet1:
    peer: leaf03-dc1
    peer_interface: Ethernet5
    peer_type: l3leaf
    description: LEAF03-DC1_Ethernet5
    type: switched
    shutdown: false
    channel_group:
      id: 1
      mode: active
  Ethernet2:
    peer: leaf04-dc1
    peer_interface: Ethernet5
    peer_type: l3leaf
    description: LEAF04-DC1_Ethernet5
    type: switched
    shutdown: false
    channel_group:
      id: 1
      mode: active
mlag_configuration:
  domain_id: dc1_leaf2
  local_interface: Vlan4094
  peer_address: 10.255.252.9
  peer_link: Port-Channel3
  reload_delay_mlag: 300
  reload_delay_non_mlag: 330
ip_igmp_snooping:
  globally_enabled: true
